### PR TITLE
Add test DS9_REGION_IMPORT_DOS

### PR DESCRIPTION
**Pull request by zarda**
From #174, test to import DS9 region file, which are made on DOS and UNIX platform.

### CODE REVIEW

**Comment by acdo2002** [comment]
So far there is no "1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0" on "/scratch/images/set_QA/set_QA_regionTest".

**Comment by zarda** [comment]
> So far there is no "1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0" on "/scratch/images/set_QA/set_QA_regionTest".

Sorry about not give a note.
Please move this file from /carta_ds9_regions to /set_QA

**Comment by ajm-asiaa** [comment]
> > So far there is no "1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0" on "/scratch/images/set_QA/set_QA_regionTest".
> 
> Sorry about not give a note.
> Please move this file from /carta_ds9_regions to /set_QA

OK. It is done.

**Comment by ajm-asiaa** [comment]
This works fine on MacOS, but I seem to have on issue on Ubuntu. What could I be doing wrong? 

```
FAIL src/test/DS9_REGION_IMPORT_DOS.test.ts
  DS9_REGION_IMPORT_DOS: Testing import of DS9 region files made on DOS & UNIX platform
    Go to "set_QA/set_QA_regionTest" folder and open image "1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0"
      Import "GRB200219A_reg_dos.txt"
        ✕ IMPORT_REGION_ACK0 should return within 500ms (36ms)
        ✕ IMPORT_REGION_ACK0.success = true
        ✕ Length of IMPORT_REGION_ACK0.region = 2
      Import "GRB200219A_reg_unix.txt"
        ✓ IMPORT_REGION_ACK1 should return within 500ms (1ms)
        ✕ IMPORT_REGION_ACK1.success = true
        ✕ Length of IMPORT_REGION_ACK1.region = 2
      Assert both imported regions are equal
        ✓ IMPORT_REGION_ACK0 = IMPORT_REGION_ACK1

  ● DS9_REGION_IMPORT_DOS: Testing import of DS9 region files made on DOS & UNIX platform › Go to "set_QA/set_QA_regionTest" folder and open image "1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0" › Import "GRB200219A_reg_dos.txt" › IMPORT_REGION_ACK0 should return within 500ms

    Failed: Object {
      "message": "Region importer failed.",
      "severity": "ERROR",
      "tags": Array [
        "import",
      ],
    }

      110 |         for (const [idxRegion, regionAck] of assertItem.importRegionAck.entries()) {
      111 |             describe(`Import "${assertItem.importRegion[idxRegion].file}"`, () => {
    > 112 |                 test(`IMPORT_REGION_ACK${idxRegion} should return within ${importTimeout}ms`, async () => {
          |                 ^
      113 |                     await Connection.send(CARTA.ImportRegion, assertItem.importRegion[idxRegion]);
      114 |                     importRegionAck.push(await Connection.receive(CARTA.ImportRegionAck) as CARTA.ImportRegionAck);
      115 |                 }, importTimeout);
```

**Comment by acdo2002** [comment]
It passed with Socketicd (CentOS) & almac (MasOS).
However it fails with my laptop (Ubuntu backend), it looks like the Ubuntu backend cannot open "1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0".
The backend log shows:

> 2021-02-03 06:04:26	SEVERE	TableLogSink::TableLogSink (file /build/carta-casacore-GjcRTt/carta-casacore-2020.8.20~focal/casa6/casatools/casacore/tables/LogTables/TableLogSink.cc, line 102)	/home/mylin/carta-test-img/set_QA/set_QA_regionTest/1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0/logtable does not exist or is not readable

**Comment by ajm-asiaa** [comment]
@acdo2002 In your error message, does the TableLogSink.cc file really exist at that location: `/build/carta-casacore-GjcRTt/carta-casacore-2020.8.20~focal/casa6/casatools/casacore/tables/LogTables/TableLogSink.cc`?

**Review by ajm-asiaa — APPROVED** [review]
This works for me now on Ubuntu with ws://, and still works on MacOS with ws:// 
So I'd be inclined to approve it.

**Comment by acdo2002** [comment]
@ajm-asiaa Yes, you are right, after I copy the logtable to `root_path/set_QA/set_QA_regionTest/1582287955_sdp_l0.GRB200219A_nouvcut_briggs-0.3.image.tt0` then it is PASSED!!!
Sorry Heng-tai, I did not copy the folder properly...

**Review by acdo2002 — APPROVED** [review]

**Pull request merged**
