### PR TITLE
Test to open images and file information

### PR DESCRIPTION
**Pull request by zarda**
For #165 and #221, to test requesting the information of files and opening the images.

OPEN_IMAGE_PV will test the image containing pv data.
OPEN_IMAGE_CASA_VARIENTS will test the variant casa images.
FILEINFO_CASA_VARIENTS will check out the file info in the variant casa images.

Use [Jest.toMatchSnapshot()](https://jestjs.io/docs/expect#tomatchsnapshotpropertymatchers-hint) to see if the responding message is as exact as expected.

### CODE REVIEW

**Review by ajm-asiaa — COMMENTED** [review]
It works on Ubuntu. 

I copied over the new `/set_casaImageVarients` folder to the Mac, but unfortunately there is a problem with these new 'snapshot' files. For example,

    -     "date": "1575483289",
    +     "date": "1618195790",
          "name": "componentlist.image",
          "size": "1880126",

    -     "date": "1575483289",
    +     "date": "1618195859",
          "name": "concatenated.image",
          "size": "1134908779",

                "entryType": "FLOAT",
                "name": "OBSDEC",
    -           "numericValue": 13.277961108781836,
    +           "numericValue": 13.277961108781838,
                "value": "1.327796110878E+01",

Could it be that the image files on the Mac are different (older versions) compared the ones currently on almalustre?

**Comment by zarda** [comment]
If the header item is trivial, we might skip it. Such as the file 'date' of creation.
The precision of float number would be considered as a test case.

**Comment by ajm-asiaa** [comment]
Now the only problem is the float number in `OPEN_IMAGE_CASA_VARIENTS.test.ts`

    -         "numericValue": 13.277961108781836,
    +         "numericValue": 13.277961108781838,
              "value": "1.327796110878E+01",

How accurate does it need to be?

**Comment by zarda** [comment]
Suppose it's enough to set 4 digits here.

**Comment by kswang1029** [comment]
it is better to use relative error and tolerance.

**Comment by zarda** [comment]
How about verify its digits after transferring this float number to an exponential float number?
`0.001234321` -> `1.234321E-3` -> `1.234E-3`
........................................^

**Comment by acdo2002** [comment]
So far testing with Ubuntu and MacOS, they works fine with ws. 
Even generating the __snapshots__ folder at the first run.

**Review by ajm-asiaa — APPROVED** [review]
Good. Seems fine on Ubuntu and MacOS now.

**Pull request merged**
