### PR TITLE
Patch for file info testing

### PR DESCRIPTION
**Pull request by zarda**
Request BASE for request of fileInfo and check out the value in format of float for extended info.
This patch should solve the inconsistent of file extended information between mac & linux.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
This is great! Now we won't need Mac-only versions of the tests!

These ones now work fine on MacOS:
src/test/FILEINFO_CASA.test.ts
src/test/FILEINFO_FITS.test.ts
src/test/FILEINFO_FITS_MULTIHDU.test.ts
src/test/FILEINFO_MIRIAD.test.ts

Only the HDF5 one does not:
src/test/FILEINFO_HDF5.test.ts

        ✕ assert FILE_INFO_RESPONSE.file_info_extended.computed_entries (4ms)
        ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (7ms)

```
    Expected value: {"name": "Image reference pixels", "value": "[321.0, 401.0]"}
    Received array: [{"name": "Name", "value": "M17_SWex.hdf5"}, {"name": "HDU", "value": "0"}, {"name": "Shape", "value": "[640, 800, 25, 1]"}, {"entryType": "INT", "name": "Number of channels", "numericValue": 25, "value": "25"}, {"entryType": "INT", "name": "Number of stokes", "numericValue": 1, "value": "1"}, {"name": "Coordinate type", "value": "Right Ascension, Declination"}, {"name": "Projection", "value": "SIN"}, {"name": "Image reference pixels", "value": "[321, 401]"}, {"name": "Image reference coords", "value": "[18:20:21.0000, -016.12.10.0000]"}, {"name": "Image ref coords (deg)", "value": "[275.088 deg, -16.2028 deg]"}, {"name": "Pixel increment", "value": "-0.4\", 0.4\""}, {"name": "Celestial frame", "value": "ICRS"}, {"name": "Spectral frame", "value": "LSRK"}, {"name": "Velocity definition", "value": "RADIO"}, {"name": "Pixel unit", "value": "Jy/beam"}, {"name": "Restoring beam", "value": "2.06105\" X 1.49126\", -74.6267 deg"}]
```

Is this due to the changes of the HDF5 converter API that you mentioned?

**Comment by zarda** [comment]
Thanks for review. The bug has fixed.

**Comment by ajm-asiaa** [comment]
Now it is down to 1 error:

        ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (7ms)

  ● FILEINFO_HDF5: Testing if info of an HDF5 image file is correctly delivered by the backend › Go to "set_QA" folder › query the info of file : M17_SWex.hdf5 › assert FILE_INFO_RESPONSE.file_info_extended.header_entries

    TypeError: Cannot read property 'value' of undefined

      378 |             test(`assert FILE_INFO_RESPONSE.file_info_extended.header_entries`, () => {
      379 |                 assertItem.fileInfoResponse.fileInfoExtended['0'].headerEntries.map((entry: CARTA.IHeaderEntry, index) => {
    > 380 |                     expect(parseFloat(FileInfoResponse.fileInfoExtended['0'].headerEntries.find(f => f.name == entry.name).value)).toEqual(parseFloat(entry.value));
          |                                       ^
      381 |                 });
      382 |             });
      383 |         });

**Comment by acdo2002** [comment]
This may due to 
{ value: "1", entryType: 2, numericValue: 1 },
Since this item has no name to match according to the code.

**Comment by zarda** [comment]
> This may due to
> { value: "1", entryType: 2, numericValue: 1 },
> Since this item has no name to match according to the code.

Could we give it an empty name, like 
```
{name: "", ...} 
```
?

**Comment by acdo2002** [comment]
I know how to modify the header in fits file, perhaps I can try for hdf5 file too.

**Comment by kswang1029** [comment]
@acdo2002 why do we need to modify headers?

**Comment by zarda** [comment]
We might also need to update the testing images on github to match the testing version. A new `M17_SWex.hdf5` for example.

**Comment by acdo2002** [comment]
@kswang1029 
Because we expect to see "{name: "", value: "1", entryType: 2, numericValue: 1 }" but hdf5 header shows {value: "1", entryType: 2, numericValue: 1 } now.

or we should ask for modify the hdf5 converter to give this item an empty name (I prefer this way). either way should be fine.

**Comment by kswang1029** [comment]
which image is it?

**Comment by zarda** [comment]
> @kswang1029
> Because we expect to see "{name: "", value: "1", entryType: 2, numericValue: 1 }" but hdf5 header shows {value: "1", entryType: 2, numericValue: 1 } now.
> 
> or we should ask for modify the hdf5 converter to give this item an empty name (I prefer this way). either way should be fine.

Or should we skip the items with empty name, since it might be a trivial item.

**Comment by acdo2002** [comment]
@kswang1029 M17_SWex.hdf5

**Comment by kswang1029** [comment]
please simply skip the test for headerEntries[70]. @acdo2002 please file an issue to https://github.com/idia-astro/fits2idia

**Comment by zarda** [comment]
@ajm-asiaa It should pass all at the moment.

**Review by acdo2002 — CHANGES_REQUESTED** [review]
Could you remove *-Mac.test.ts? because now FILEINFO* (skip hdf5) can work properly with MacOS :)

**Comment by ajm-asiaa** [comment]
@zarda Which `M17_SWex.hdf5` file should we use?

If I copy out the one in `carta-backend-ICD-test/public/set_QA/M17_SWex.hdf5.zip` and unzip it, it seems to be the wrong size?

>         ✕ FILE_INFO_RESPONSE.file_info.size = 185333128 (5ms)

The old image seems to be the correct size, but it is still seems to be giving the same error:

>         ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (13ms)
> 
>     TypeError: Cannot read property 'value' of undefined

**Comment by kswang1029** [comment]
Please use the image generated with the latest convertor

**Comment by zarda** [comment]
> @zarda Which `M17_SWex.hdf5` file should we use?
> 
> If I copy out the one in `carta-backend-ICD-test/public/set_QA/M17_SWex.hdf5.zip` and unzip it, it seems to be the wrong size?
> 
> > ```
> >     ✕ FILE_INFO_RESPONSE.file_info.size = 185333128 (5ms)
> > ```
> 
> The old image seems to be the correct size, but it is still seems to be giving the same error:
> 
> > ```
> >     ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (13ms)
> > 
> > TypeError: Cannot read property 'value' of undefined
> > ```

This hdf5 image is 
```
SCHEMA_VERSION = 0.3
HDF5_CONVERTER = hdf_convert
HDF5_CONVERTER_VERSION = 0.1.13
```
Suppose it's new one.

**Comment by ajm-asiaa** [comment]
Now that I copied the new M17_SWex.hdf5 onto the Mac server, it is reporting the wrong file size...

>         ✕ FILE_INFO_RESPONSE.file_info.size = 185331280 (3ms)
> 
>     Expected: "185331280"
>     Received: "185333128"

**Review by acdo2002 — APPROVED** [review]
work fine with socketdev

**Review by ajm-asiaa — APPROVED** [review]
Seems good now!

**Pull request merged**
