### PR TITLE
Mylin/update fileinfo 07 oct2020

### PR DESCRIPTION
**Pull request by acdo2002**
Update the FILEINFO*.test.ts in order to pass the CentOS server
including:
FILEINFO.test.ts
FILEINFO_CASA.test.ts 
FILEINFO_FITS.test.ts 
FILEINFO_FITS_MULTIHDU.test.ts 
FILEINFO_HDF5.test.ts
FILEINFO_MIRIAD.test.ts

### CODE REVIEW

**Review by zarda — APPROVED** [review]

**Comment by ajm-asiaa** [comment]
@acdo2002 It seems to have a problem on MacOS with these tests:

```
        ✕ assert FILE_INFO_RESPONSE.file_info_extended.computed_entries (3ms)
        ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (8ms)
```
I'm not sure why?

It might be unrelated, but I also see these warnings:

```
  console.warn src/test/FILEINFO.test.ts:649
    Error message from reading "no_such_file.image": File no_such_file.image does not exist.

  console.warn src/test/FILEINFO.test.ts:649
    Error message from reading "broken_header.miriad": Image must be 2D, 3D or 4D.
```

I can find `broken_header.miriad`, but can not find `no_such_file.image`

**Comment by acdo2002** [comment]
@ajm-asiaa Hi Anthony,
About the `console.warn` message, they will be fine, it means they pass the test successfully! Just print out the error test result.

About a problem with MacOS.
Follow our discussion last week, I attached additional six files in this branch, please check them:
FILEINFO-Mac.test.ts
FILEINFO_CASA-Mac.test.ts
FILEINFO_FITS-Mac.test.ts
FILEINFO_FITS_MULTIHDU-Mac.test.ts
FILEINFO_HDF5-Mac.test.ts
FILEINFO_MIRIAD-Mac.test.ts

**Review by ajm-asiaa — APPROVED** [review]
Nice work @acdo2002! I just tried the new Mac versions of the tests on MacOS and they all seem to work.

**Comment by kswang1029** [comment]
@acdo2002 @ajm-asiaa Why do we need Mac-specific tests for file info?

**Comment by ajm-asiaa** [comment]
@kswang1029 MacOS appears to deal with header values slightly differently than Linux.
e.g.
Linux: `{ name: "Image reference pixels", value: "[321, 401]" }`
MacOS ` { name: "Image reference pixels", value: "[321.0, 401.0]" }`

Linux `numericValue: 2225142.180268967`
MacOS `numericValue: 2225142.1802689666`

I'm not sure if it is due to different versions of the cfitsio library, or some other library version or compiler difference.
CentOS7 is using cfitsio version 3.370
Ubuntu is using cfitsio version 3.370
MacOS is using cfitsio version 3.490

**Comment by kswang1029** [comment]
@ajm-asiaa in this case, wouldn't be better to have _one_ test script and make conditional tests based on OS type? The would be easier for future maintenance.

**Comment by acdo2002** [comment]
@kswang1029  Anthony and I thought this method before, however when I check the ICD message, so far there is no message containing the server OS information. 
So there are two solutions:
(1) FILEINFO for Mac version, since we already know the OS system when we run the ICD tests.
(2) append a serverOS into ICD message (should update the backend and the protobuf)

**Pull request merged**
