### PR TITLE
Mylin/#206 modify animator test

### LINKED ISSUE #206: Improve ICD test reliability: animator 2
I notice on MacOS that the `src/test/ANIMATOR_CONTOUR_MATCH.test.ts` test sometimes fails. 
It fails because the backend has crashed from the previous test.
The previous test is `src/test/ANIMATOR_PLAYBACK.test.ts` however, that appears to pass fine.

I tried running the animator tests in sequence on MacOS, and I found the backend crashes with the following error:
```
carta_backend(19219,0x110a9ce00) malloc: *** error for object 0x7000000010: pointer being freed was not allocated
carta_backend(19219,0x110a9ce00) malloc: *** set a breakpoint in malloc_error_break to debug
```

Perhaps that the reason? What could be causing it?

### PR DESCRIPTION
**Pull request by acdo2002**
Fixed #206 
src/test/CLOSE_FILE_ANIMATION.test.ts should run under "wss://carta.asiaa.sinica.edu.tw/socketdev", otherwise the path may not be correct. 

I have improved the tests, which are related to "AnimatorFlowControl" ICD message. I check the ubuntu(my laptop), centos(acdc), and MacOS(almac), they should not generate the remaining sessions in the backend log.

I also increase the "playAnimator" timeout (to 20000ms), since I found if using wss to the server, the previous (10000 ms) may not be enough.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@acdo2002 I'm just wondering, previously I was running the following Animator tests:

> src/test/ANIMATOR_DATA_STREAM.test.ts
> src/test/ANIMATOR_NAVIGATION.test.ts
> src/test/ANIMATOR_PLAYBACK.test.ts
> src/test/ANIMATOR_CONTOUR_MATCH.test.ts
> src/test/ANIMATOR_CONTOUR.test.ts

Are `ANIMATOR_DATA_STREAM` and `ANIMATOR_NAVIGATION` still current tests that were unaffected by the issues, or are they deprecated tests?

**Comment by acdo2002** [comment]
@ajm-asiaa  I suppose these two tests are fine, because I run them and check the backend log, there is no warning message, and there is no remaining session as well.

**Review by ajm-asiaa — CHANGES_REQUESTED** [review]
Good. These seem to run fine now.

I didn't have `CLOSE_FILE_ANIMATION.test.ts` in the set of Jenkins tests. Maybe I missed it previously due to the file name? Would it be better to rename it as `ANIMATOR_CLOSE_FILE.test.ts` to be more consistent with the other "ANIMATOR" tests?

Plus it seems to work OK with a local ws:// backend, so it doesn't seem to be limited to "wss://carta.asiaa.sinica.edu.tw/socketdev". That would be bad anyway in case someone wanted to run the ICD tests at another institution.

**Comment by acdo2002** [comment]
@ajm-asiaa 
I have renamed the test to `ANIMATOR_CLOSE_FILE.test.ts`. 
This test was developed with CLOSE_FILE related ICD tests, I guess the implementation time is later than ANIMATOR related to ICD tests.

**Comment by ajm-asiaa** [comment]
@acdo2002 Oh I'm sorry, I didn't see the series of `CLOSE_FILE` tests. In that case, would be better to keep it in the `CLOSE_FILE` series? @kswang1029 What do you think?

**Comment by kswang1029** [comment]
@ajm-asiaa I don't have preference as long as different kinds of tests are categorized well to developers.

**Comment by ajm-asiaa** [comment]
@acdo2002 I'm sorry about the trouble, but could you rename the file back to `CLOSE_FILE_ANIMATION.test.ts`? That might be best.

**Comment by acdo2002** [comment]
@ajm-asiaa That's fine : ) 
I change the name back to `CLOSE_FILE_ANIMATION.test.ts`

**Review by ajm-asiaa — APPROVED** [review]

**Pull request merged**
