### PR TITLE
Patch for #134 match wide

### PR DESCRIPTION
**Pull request by zarda**
Added a testing for wide field image.
Update the regions to show more cases of inconsistent statistical results.

Known issues:
There are many failures in these tests at the moment.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
I just tried on MacOS. `src/test/MATCH_SPATIAL.test.ts` and `src/test/MATCH_SPECTRAL.test.ts` work fine.

`src/test/MATCH_STATS.test.ts` and `MATCH_STATS_WIDE.test.ts` have several problems e.g. 

``` ● MATCH_STATS: Testing region stats with spatially and spectrally matched images › Test if the stats results are equal › Assert the NumPixels of region 1 for first image equal to that for the second image

    expect(received).toBeCloseTo(expected, precision)

    Expected: 90461
    Received: 90601

    Expected precision:    4
    Expected difference: < 0.00005
    Received difference:   140

      197 |                         expect(Object.is(left, right)).toBe(true);
      198 |                     } else {
    > 199 |                         expect(left).toBeCloseTo(right, assertItem.precisionDigits);
          |                                      ^
      200 |                     }
      201 |                 });
      202 |             }

      at Object.test (src/test/MATCH_STATS.test.ts:199:38)
```
and 

```● MATCH_STATS: Testing region stats with spatially and spectrally matched images › Test if the stats results are equal › Assert the SumSq of region 3 for first image equal to that for the second image

    expect(received).toBeCloseTo(expected, precision)

    Expected: 2.5568254469583875
    Received: 2.5568874866756657

    Expected precision:    4
    Expected difference: < 0.00005
    Received difference:   0.0000620397172781395

      197 |                         expect(Object.is(left, right)).toBe(true);
      198 |                     } else {
    > 199 |                         expect(left).toBeCloseTo(right, assertItem.precisionDigits);
          |                                      ^
      200 |                     }
      201 |                 });
      202 |             }

      at Object.test (src/test/MATCH_STATS.test.ts:199:38)
```
Plus errors such as:
```
 ● MATCH_STATS_WIDE: Testing region stats with spatially and spectrally matched wide field images › Test if the stats results are equal › Assert the Min of region 2 for first image equal to that for the second image

    TypeError: Cannot read property 'statistics' of undefined

      192 |             for (const [statsIdx, statsType] of assertItem.setStatsRequirements[0][regionIdx].stats.entries()) {
      193 |                 test(`Assert the ${CARTA.StatsType[statsType]} of region ${region.regionId} for first image equal to that for the second image`, () => {
    > 194 |                     const left = RegionStatsData.find(data => data.fileId == assertItem.openFile[0].fileId && data.regionId == region.regionId).statistics.find(data => data.statsType == statsType).value;
          |                                  ^
      195 |                     const right = RegionStatsData.find(data => data.fileId == assertItem.openFile[1].fileId && data.regionId == region.regionId).statistics.find(data => data.statsType == statsType).value;
      196 |                     if (isNaN(left) || isNaN(right)) {
      197 |                         expect(Object.is(left, right)).toBe(true);

      at Object.test (src/test/MATCH_STATS_WIDE.test.ts:194:34)
```

Is this a combination of MacOS vs Linux differences plus ICD changes?

**Review by ajm-asiaa — CHANGES_REQUESTED** [review]
I can only approve `src/test/MATCH_SPATIAL.test.ts` and `src/test/MATCH_SPECTRAL.test.ts`. 

It would be better if `src/test/MATCH_STATS.test.ts` and `src/test/MATCH_STATS_WIDE.test.ts` could be shown to pass too.

**Comment by zarda** [comment]
The failures are anticipated outcomes as far as the backend being fixed. We intend to reveal this problem. Please refer to [design doc](https://docs.google.com/document/d/197Y1rrj7i7J1PP6NvNJuf6UK-_ZTZjc8ybD_xG6GHXw/edit#heading=h.s7sgjlz4yzg8).

**Comment by zarda** [comment]
MATCH_STATS & MATCH_STATS_WIDE could pass at the current branch but tests with a suffix _BORDERLINE will fail till' the backend being updated.

**Review by ajm-asiaa — APPROVED** [review]
`src/test/MATCH_STATS.test.ts` and `src/test/MATCH_STATS_WIDE.test.ts` now seem to pass OK on MacOS.

**Pull request merged**
