### PR TITLE
Mylin/#100 raster tiles

### PR DESCRIPTION
**Pull request by acdo2002**
#100 
There are two problems: 
(1) TILE_DATA_REQUEST-v14.test.ts

ADD_REQUIRED_TILES[33558529, 33562626, 33566723, 33570820]
✕ RASTER_TILE_DATA x3 should arrive within 3000 ms(3001ms)
✕ Backend be still alive(1ms)
ADD_REQUIRED_TILES[33570820]
✓ RASTER_TILE_DATA should NOT arrive within 3000 ms(1503ms)
✕ Backend be still alive(1ms)
ADD_REQUIRED_TILES[50364424]
✓ RASTER_TILE_DATA should NOT arrive within 3000 ms(1505ms)
✕ Backend be still alive(1ms)

In the document, input four tiles (3 valid & 1 invalid) as request, then the backend will crash, below is a summary of various inputs:

send ADD_REQUIRED_TILES[33558529, 33562626, 33566723, 33570820] * 33570820 is an invalid tile
Backend Log shows:
// Jest only received one returned message from Backend {RasterTileSync: [RasterTileSync {}]} as Stream
// No RASTER_TILE_DATA returned
// BackendLog:
// Mean filter 0x0 raster data to 0x0 in 0.003 ms at 0 MPix/s
// Bus error(core dumped)
// or BackendLog:
// Mean filter 0x0 raster data to 0x0 in 0.002 ms at 0 MPix/s
// Segmentation fault(core dumped)

send ADD_REQUIRED_TILES[33570820] * 33570820 is an invalid tile
Backend Log shows:
// Mean filter 0x0 raster data to 0x0 in 0.01 ms at 0 MPix / s 
// Segmentation fault(core dumped)

send ADD_REQUIRED_TILES[50364424] * 50364424 is an invalid tile
Backend Log shows:
// BackendLog:
// Mean filter 0x0 raster data to 0x0 in 0.012 ms at 0 MPix / s 
// Segmentation fault(core dumped)
// or BackendLog:
// Mean filter 0x0 raster data to 0x0 in 0.002 ms at 0 MPix / s 
// Bus error(core dumped)

(2) TILE_DATA_ORDER-v14.test.ts
✕ Tile "16777216" should return within the 2nd rank (2ms)
If we request four tiles, the first tile will not always return with 2nd rank.

I test with socketdev (server): Sequence of returned tiles(1-indexed) 
socketdev results: 8 failed; 2 passed
[4, 2, 3, 1]
[3, 1, 4, 2]
[3, 1, 2, 4]
[2, 3, 4, 1]
[3, 2, 4, 1]
[3, 2, 4, 1]
[4, 2, 3, 1]
[4, 2, 3, 1]
[1, 3, 4, 2]
[3, 2, 4, 1]

I test another socketicd: Sequence of returned tiles(1-indexed) 
socketicd results: 2 failed; 8 passed
[1, 4, 2, 3]
[1, 2, 4, 3]
[1, 4, 2, 3]
[1, 4, 3, 2]
[1, 4, 2, 3]
[3, 4, 2, 1]
[1, 3, 4, 2]
[1, 4, 3, 2]
[1, 2, 3, 4]
[2, 4, 1, 3]

Despite the sequence of the first tile is not always within 2nd rank, all tiles returned properly.

### CODE REVIEW

**Comment by kswang1029** [comment]
@acdo2002 thanks. For issue 2, please remove the test for "tiles=[16777216, 16781312, 16781313, 16777217]"

For issue 1, we will need some discussions in the slack backend channel.

**Comment by kswang1029** [comment]
@acdo2002 how do you verify the backend is still alive? (✕ Backend be still alive(1ms))

**Comment by acdo2002** [comment]
@kswang1029  
check the websocket Client connection.readyState to be open.
same to the ACCESS_CARTA_DEFAULT.test.ts

socektdev(server) will restart automatically once the backend crashed. 
However, for the socketicd(acdc/mingyi) I did not set the automatically restart with these tests.

**Comment by kswang1029** [comment]
> ✓ RASTER_TILE_DATA should NOT arrive within 3000 ms(1505ms)
✕ Backend be still alive(1ms)

This refers to the test of requesting a single invalid tile and check if the backend is still alive. So in this case, the backend crashed?

**Comment by ajm-asiaa** [comment]
@acdo2002 Nice work! I am testing with the carta-backend running on MacOS, and the ICD tests running from an Ubuntu machine. 
`CHECK_RASTER_TILE_DATA-v14.test.ts` consistently passes when running multiple times.
`TILE_DATA_ORDER-v14.test.ts` did fail a few times due to the segmentation fault, but now with your new commit (remove the test for tiles=[16777216, 16781312, 16781313, 16777217] of… ), it consistently passes too.
`TILE_DATA_REQUEST-v14.test.ts` is problematic. 

Running the backend with the `-debug 3 -verbose True` flags, provides more information. I wonder if the last line is the reason?
`Mean filter 0x0 raster data to 0x0 in 0.001 ms at 0 MPix/s `
Could it be a 'nan' problem?

```

Session 1 (Mon Jun 15 16:23:16 2020): Client 1 [::ffff:127.0.0.1] Connected. Num sessions: 1
2020-06-15 08:23:17	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
Load 4096x4096 image to cache in 233.062 ms at 71.9861 MPix/s
Calculate min/max value in 45.996 ms at 364.754 MPix/s
Fill image histogram in 129.907 ms at 129.148 MPix/s
Mean filter 2048x2048 raster data to 256x256 in 78.024 ms at 0.839947 MPix/s 
Mean filter 2048x2048 raster data to 256x256 in 78.14 ms at 0.8387 MPix/s 
Mean filter 2048x2048 raster data to 256x256 in 78.148 ms at 0.838614 MPix/s 
Mean filter 2048x2048 raster data to 256x256 in 78.381 ms at 0.836121 MPix/s 
Get tile data group in 86.625 ms
Mean filter 1024x1024 raster data to 256x256 in 19.885 ms at 3.29575 MPix/s 
Mean filter 1024x1024 raster data to 256x256 in 20.991 ms at 3.1221 MPix/s 
Mean filter 1024x1024 raster data to 256x256 in 21.005 ms at 3.12002 MPix/s 
Compress 256x256 tile data in 2.142 ms at 30.5957 MPix/s
Compress 256x256 tile data in 2.076 ms at 31.5684 MPix/s
Compress 256x256 tile data in 2.112 ms at 31.0303 MPix/s
Get tile data group in 27.31 ms
Mean filter 0x0 raster data to 0x0 in 0.001 ms at 0 MPix/s 
zsh: segmentation fault 
```
```

**Comment by kswang1029** [comment]
@ajm-asiaa your question is similar to the one I raised. @acdo2002 please confirm the case: if we request a single invalid tile, will the backend crash? 

> Mean filter 0x0 raster data to 0x0 in 0.001 ms at 0 MPix/s 
zsh: segmentation fault 

This appears to be the case but need @acdo2002 to confirm.

**Comment by acdo2002** [comment]
Yes, because everything works fine with the valid three tiles [33558529,33562626,33566723]
No matter you add a line to check whether the backend is alive.
Once you insert the invalid tile, the backend will crash (I monitor ./backend verbose=true and copy the backendlog directly).

**Comment by kswang1029** [comment]
@acdo2002 ok, please remove the test of requesting a single invalid tile. For the 3-vaild + 1-invalid test, let's see what Angus thinks.

**Comment by acdo2002** [comment]
Based on the updated backend branch (e3f3bea 5006 2020-06-17 09:58:45 UTC), I slightly improve the code. However the issue is still there.
If I insert any wrong tile (e.g. 3 valid + 1 invalid), the backend will crash.
 FAIL  src/test/TILE_DATA_REQUEST-v14.test.ts (13.011s)
  CHECK_RASTER_TILE_DATA test: Testing data values at different layers in RASTER_TILE_DATA
    ✓ (Step 0) Connection open? |  (3ms)
    read the file "cluster_04096.fits" on folder "set_QA"
      ✓ OpenFileAck? |  (367ms)
      ✓ RegionHistogramData (would pass over if trying several times)? |  (15ms)
      ✓ RasterTileData * 4 + SpatialProfileData * 1 + RasterTileSync *2 (start & end)? | (452ms)
      (Step1-3) Check each RASTER_TILE_DATA
        ✓ (#0)RASTER_TILE_DATA.tiles.length = 1 |
        ✓ (#0)RASTER_TILE_DATA.tiles[0].x = 0 & RASTER_TILE_DATA.tiles[0].y = 0 & RASTER_TILE_DATA.tiles[0].layer = 1| (1ms)
        ✓ (#1)RASTER_TILE_DATA.tiles.length = 1 |
        ✓ (#1)RASTER_TILE_DATA.tiles[0].x = 1 & RASTER_TILE_DATA.tiles[0].y = 0 & RASTER_TILE_DATA.tiles[0].layer = 1| (1ms)
        ✓ (#2)RASTER_TILE_DATA.tiles.length = 1 |
        ✓ (#2)RASTER_TILE_DATA.tiles[0].x = 0 & RASTER_TILE_DATA.tiles[0].y = 1 & RASTER_TILE_DATA.tiles[0].layer = 1|
        ✓ (#3)RASTER_TILE_DATA.tiles.length = 1 |
        ✓ (#3)RASTER_TILE_DATA.tiles[0].x = 1 & RASTER_TILE_DATA.tiles[0].y = 1 & RASTER_TILE_DATA.tiles[0].layer = 1|
      ADD_REQUIRED_TILES 33558529,33562626,33566723
        ✓ RASTER_TILE_DATA x3 should arrive within 3000 ms (72ms)
        ✓ Backend be still alive (After send/receive)
        (Step4-7) Check each RASTER_TILE_DATA
          ✓ (#0)RASTER_TILE_DATA.tiles.length = 1 |
          ✓ (#0)RASTER_TILE_DATA.tiles[0].x = 1 & RASTER_TILE_DATA.tiles[0].y = 1 & RASTER_TILE_DATA.tiles[0].layer = 2|
          ✓ (#1)RASTER_TILE_DATA.tiles.length = 1 | (1ms)
          ✓ (#1)RASTER_TILE_DATA.tiles[0].x = 2 & RASTER_TILE_DATA.tiles[0].y = 2 & RASTER_TILE_DATA.tiles[0].layer = 2| (1ms)
          ✓ (#2)RASTER_TILE_DATA.tiles.length = 1 |
          ✓ (#2)RASTER_TILE_DATA.tiles[0].x = 3 & RASTER_TILE_DATA.tiles[0].y = 3 & RASTER_TILE_DATA.tiles[0].layer = 2| (1ms)
      ADD_REQUIRED_TILES 33558529,33562626,33566723,33570820
        ✕ RASTER_TILE_DATA x3 should arrive within 3000 ms (3002ms)
        ✕ Backend be still alive (After send/receive) (3ms)

// The backend Log shows:
// Mean filter 0x0 raster data to 0x0 in 0.003 ms at 0 MPix/s
// Bus error(core dumped)
// or the BackendLog  Log shows::
// Mean filter 0x0 raster data to 0x0 in 0.002 ms at 0 MPix/s
// Segmentation fault(core dumped)

**Comment by kswang1029** [comment]
Please just comment out the test with 3-valid+1-invalid tiles. A backend issue has been created for fixing this.

**Comment by acdo2002** [comment]
@ajm-asiaa , I have modified those files name without `-v14` and commit them.  
This issue I have asked/discussed with Hengtai before, the ICD version will follow the *.test.ts, not necessary to give them a name mark.

**Pull request merged**
