### PR TITLE
Add test for BEAM_TABLE of OPEN_FILE_ACK

### PR DESCRIPTION
**Pull request by zarda**
For #173, additional test for open an image with multiple beam tables.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
For `src/test/OPENFILE_CASA_BEAMTABLE.test.ts` on MacOS, I get:

```
    expect(received).toEqual(expected) // deep equality

    Expected: "1864981459"
    Received: "1864975311"
```
Is this another case of values being different on MacOS?

I deleted the existing `SDC335.579-0.292.spw0.line.image` on the Mac and copied over the one on almalustre (set_QA/SDC335.579-0.292.spw0.line.image) just in case the Mac had an outdated version of the file. But it still has the same issue.

In `src/test/OPENFILE_FITS_BEAMTABLE.test.ts`, where is the ` SDC335.579-0.292.spw0.line.fits` file? 
I can't find it in /set_QA on almalustre.

**Comment by zarda** [comment]
> For `src/test/OPENFILE_CASA_BEAMTABLE.test.ts` on MacOS, I get:
> 
> ```
>     expect(received).toEqual(expected) // deep equality
> 
>     Expected: "1864981459"
>     Received: "1864975311"
> ```
> 
> Is this another case of values being different on MacOS?
> 
> I deleted the existing `SDC335.579-0.292.spw0.line.image` on the Mac and copied over the one on almalustre (set_QA/SDC335.579-0.292.spw0.line.image) just in case the Mac had an outdated version of the file. But it still has the same issue.

Have fixed it, thanks.

> 
> In `src/test/OPENFILE_FITS_BEAMTABLE.test.ts`, where is the ` SDC335.579-0.292.spw0.line.fits` file?
> I can't find it in /set_QA on almalustre.

I can get a file link in /set_QA.

**Comment by acdo2002** [comment]
Since I can download the casa file (.image) and convert it to .fits via CARTA.App 1.4 release version.
These two tests are passed on my desktop (Ubuntu 20.04).

**Review by acdo2002 — APPROVED** [review]

**Review by ajm-asiaa — APPROVED** [review]
Nice! Now works for me on MacOS and Ubuntu.

**Pull request merged**
