### PR TITLE
Add test FILEINFO_FITS_NONSTANDARD

### PR DESCRIPTION
**Pull request by zarda**
For issue #185, to test the fits image with nonstandard header.

The testing images should be under /set_QA/header_issue .
@ajm-asiaa Please move it from /tmp/header_issue to /set_QA.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@zarda I'm sorry. I didn't see your comment here with the instructions of what folder to move! 

The test seems fine. Just one suggestion. Maybe you could rename the new folder "header_issue" to something else?
"issue" sounds temporary and negative.
Perhaps "nonstandard_headers" or "nonstandard_header_test"?

**Review by ajm-asiaa — APPROVED** [review]
@zarda Thanks! 
I have also just updated the folder name in the set_QA folders on almalustre and the Mac.

**Review by acdo2002 — APPROVED** [review]
Thanks Heng-tai & Anthony!
It works in socketdev, socketicd & almac MasOS.

**Comment by zarda** [comment]
> @zarda Thanks!
> I have also just updated the folder name in the set_QA folders on almalustre and the Mac.

Thanks.
I thought the image folder /images/set_QA are equal on all servers, which is mounted on.

**Pull request merged**
