### PR TITLE
Hj/#175 file info

### PR DESCRIPTION
**Pull request by zarda**
Remove the entry of request file info to be a workaround of $BASE parsing issue.
Refactor a bit function naming

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
None of the Mac specific tests seem to work. For example,

FILEINFO_CASA_Mac.test.ts

```
    TypeError: Cannot read property 'dimensions' of undefined

      328 | 
      329 |             test(`FILE_INFO_RESPONSE.file_info_extended.dimensions = ${assertItem.fileInfoResponse[0].fileInfoExtended[''].dimensions}`, () => {
    > 330 |                 expect(FileInfoResponse.fileInfoExtended[''].dimensions).toEqual(assertItem.fileInfoResponse[0].fileInfoExtended[''].dimensions);
          |                                                              ^
      331 |             });
      332 | 
      333 |             test(`FILE_INFO_RESPONSE.file_info_extended.width = ${assertItem.fileInfoResponse[0].fileInfoExtended[''].width}`, () => {

```

FILEINFO_FITS-Mac.test.ts

```
    invalid wire type 6 at offset 218

      1140 |                     break;
      1141 |                 default:
    > 1142 |                     reader.skipType(tag & 7);
           |                            ^
      1143 |                     break;
      1144 |                 }
      1145 |             }
```

**Comment by acdo2002** [comment]
Although remove the CARTA.fileInfoRequest can let the tests passed, the problem would be 
why the current backend dev cannot return the CARTA.FileListResponse when ICD tests send the CARTA.fileInfoRequest. 
The UI performance smoothly, but the ICD tests cannot repeat it.

**Comment by acdo2002** [comment]
I test with the backend on CentOS acdc & MacOS almac, They are all passed, but again, I think the problem is that we should investigate why CARTA.fileInfoRequest & CARTA.FileListResponse do not work properly with current dev backend.

**Comment by zarda** [comment]
The issue about file_info and file_list is addressed by @ajm-asiaa . Changed the protocol of websocket from the testing client side to disable the functionality of compression.

**Review by acdo2002 — APPROVED** [review]
They are all passed with the current dev on CentOS & MacOC.

**Comment by ajm-asiaa** [comment]
I'm still having trouble with all the Mac related tests for some reason.
For example `src/test/FILEINFO_MIRIAD-Mac.test.ts`. 

```
FAIL src/test/FILEINFO_MIRIAD-Mac.test.ts
  FILEINFO test: Testing if info of an image file is correctly delivered by the backend
    Go to "set_QA" folder
      query the info of file : M17_SWex.miriad
        ✓ FILE_INFO_RESPONSE should arrive within 2100 ms". (7ms)
        ✓ FILE_INFO_RESPONSE.success = true (1ms)
        ✓ FILE_INFO_RESPONSE.file_info.HDU_List = []
        ✓ FILE_INFO_RESPONSE.file_info.name = "M17_SWex.miriad" (1ms)
        ✓ FILE_INFO_RESPONSE.file_info.size = 52993642
        ✓ FILE_INFO_RESPONSE.file_info.type = 3
        ✕ FILE_INFO_RESPONSE.file_info_extended.dimensions = 4 (1ms)
        ✕ FILE_INFO_RESPONSE.file_info_extended.width = 640 (1ms)
        ✕ FILE_INFO_RESPONSE.file_info_extended.height = 800
        ✕ FILE_INFO_RESPONSE.file_info_extended.depth = 25
        ✕ FILE_INFO_RESPONSE.file_info_extended.stokes = 1
        ✕ FILE_INFO_RESPONSE.file_info_extended.stokes_vals = []
        ✕ len(FILE_INFO_RESPONSE.file_info_extended.computed_entries)==15 (1ms)
        ✕ assert FILE_INFO_RESPONSE.file_info_extended.computed_entries
        ✕ len(file_info_extended.header_entries)==68
        ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries

  ● FILEINFO test: Testing if info of an image file is correctly delivered by the backend › Go to "set_QA" folder › query the info of file : M17_SWex.miriad › FILE_INFO_RESPONSE.file_info_extended.dimensions = 4

    TypeError: Cannot read property 'dimensions' of undefined

      327 | 
      328 |             test(`FILE_INFO_RESPONSE.file_info_extended.dimensions = ${assertItem.fileInfoResponse[0].fileInfoExtended[''].dimensions}`, () => {
    > 329 |                 expect(FileInfoResponse.fileInfoExtended[''].dimensions).toEqual(assertItem.fileInfoResponse[0].fileInfoExtended[''].dimensions);
          |                                                              ^
      330 |             });
      331 | 
      332 |             test(`FILE_INFO_RESPONSE.file_info_extended.width = ${assertItem.fileInfoResponse[0].fileInfoExtended[''].width}`, () => {

      at Object.<anonymous> (src/test/FILEINFO_MIRIAD-Mac.test.ts:329:62)

```

Is there something I'm missing?

**Comment by acdo2002** [comment]
This is a little bit strange, because if I use alma as Mac server. They can pass with wss.
It looks like the file_info_extended does not catch properly.

Could you block the the failed pass (from line 333 of `FILEINFO_CASA-Mac.test.ts`)
and replace line 330 as following, let print out the return ICD message!

original line 330: 
expect(FileInfoResponse.fileInfoExtended[''].dimensions).toEqual(assertItem.fileInfoResponse[0].fileInfoExtended[''].dimensions);

replaced by:
console.log(FileInfoResponse)
console.log(FileInfoResponse.fileInfoExtended)

I guest it could be just the format problem?

**Comment by ajm-asiaa** [comment]
The Mac related tests are now passing fine for me on MacOS with ws://

> src/test/FILEINFO_CASA-Mac.test.ts
> src/test/FILEINFO_EXCEPTIONS.test.ts
> src/test/FILEINFO_FITS-Mac.test.ts
> src/test/FILEINFO_FITS_MULTIHDU-Mac.test.ts
> src/test/FILEINFO_MIRIAD-Mac.test.ts

However, now I'm having trouble on Ubuntu with ws://. But only with the `file_info_extended` parts of the tests.
e.g. `in src/test/FILEINFO_CASA.test.ts`

```
        ✕ assert FILE_INFO_RESPONSE.file_info_extended.computed_entries (5ms)

        ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (32ms)
```

```
 Expected value: {"name": "Image reference pixels", "value": "[321, 401]"}
    Received array: [{"name": "Name", "value": "M17_SWex.image"}, {"name": "Shape", "value": "[640, 800, 25, 1]"}, {"entryType": "INT", "name": "Number of channels", "numericValue": 25, "value": "25"}, {"entryType": "INT", "name": "Number of stokes", "numericValue": 1, "value": "1"}, {"name": "Coordinate type", "value": "Right Ascension, Declination"}, {"name": "Projection", "value": "SIN"}, {"name": "Image reference pixels", "value": "[321.0, 401.0]"}, {"name": "Image reference coords", "value": "[18:20:21.0000, -016.12.10.0000]"}, {"name": "Image ref coords (deg)", "value": "[275.088 deg, -16.2028 deg]"}, {"name": "Pixel increment", "value": "-0.4\", 0.4\""}, {"name": "Celestial frame", "value": "ICRS"}, {"name": "Spectral frame", "value": "LSRK"}, {"name": "Velocity definition", "value": "RADIO"}, {"name": "Pixel unit", "value": "Jy/beam"}, {"name": "Restoring beam", "value": "2.06105\" X 1.49126\", -74.6267 deg"}]
```
@zarda Has something changed in the carta_backend over the last 2 weeks?

**Comment by zarda** [comment]
> The Mac related tests are now passing fine for me on MacOS with ws://
> 
> > src/test/FILEINFO_CASA-Mac.test.ts
> > src/test/FILEINFO_EXCEPTIONS.test.ts
> > src/test/FILEINFO_FITS-Mac.test.ts
> > src/test/FILEINFO_FITS_MULTIHDU-Mac.test.ts
> > src/test/FILEINFO_MIRIAD-Mac.test.ts
> 
> However, now I'm having trouble on Ubuntu with ws://. But only with the `file_info_extended` parts of the tests.
> e.g. `in src/test/FILEINFO_CASA.test.ts`
> 
> ```
>         ✕ assert FILE_INFO_RESPONSE.file_info_extended.computed_entries (5ms)
> 
>         ✕ assert FILE_INFO_RESPONSE.file_info_extended.header_entries (32ms)
> ```
> 
> ```
>  Expected value: {"name": "Image reference pixels", "value": "[321, 401]"}
>     Received array: [{"name": "Name", "value": "M17_SWex.image"}, {"name": "Shape", "value": "[640, 800, 25, 1]"}, {"entryType": "INT", "name": "Number of channels", "numericValue": 25, "value": "25"}, {"entryType": "INT", "name": "Number of stokes", "numericValue": 1, "value": "1"}, {"name": "Coordinate type", "value": "Right Ascension, Declination"}, {"name": "Projection", "value": "SIN"}, {"name": "Image reference pixels", "value": "[321.0, 401.0]"}, {"name": "Image reference coords", "value": "[18:20:21.0000, -016.12.10.0000]"}, {"name": "Image ref coords (deg)", "value": "[275.088 deg, -16.2028 deg]"}, {"name": "Pixel increment", "value": "-0.4\", 0.4\""}, {"name": "Celestial frame", "value": "ICRS"}, {"name": "Spectral frame", "value": "LSRK"}, {"name": "Velocity definition", "value": "RADIO"}, {"name": "Pixel unit", "value": "Jy/beam"}, {"name": "Restoring beam", "value": "2.06105\" X 1.49126\", -74.6267 deg"}]
> ```
> 
> @zarda Has something changed in the carta_backend over the last 2 weeks?

This issue relates to the old problem about the difference of digit presentation between the libs of mac & linux.
The expected value: 321, for example, gets the receiving value: 321.0 insteadly.
At the moment, we check it up in the view of string rather than its value.
We will work for a better solution about this issue.

**Comment by acdo2002** [comment]
The *-Mac.test.ts are all failed with the latest commit, however if I checkout to previous commit:`761b8cd` then *-Mac.test.ts can be passed with wss on almac server.

**Comment by acdo2002** [comment]
only FILEINFO_CASA-Mac.test.ts does not pass. 
If I block line 358 and using line 359-361 then it can pass...?

**Comment by zarda** [comment]
Thanks, please correct those difference on mac server as a commit.

**Review by ajm-asiaa — APPROVED** [review]
I tried again. Very good. All Mac specific tests appear to work fine on MacOS with ws:// and the non-Mac tests appear to work fine on Ubuntu with ws://

**Pull request merged**
