### PR TITLE
Finish implementation of PER_CONTOUR_DATA_2D.test.ts

### PR DESCRIPTION
**Pull request by acdo2002**
The design document is [here](https://docs.google.com/document/d/1lU_Y5OyB7lqdZ4q2_LjnEVeTIXJj8yKl7SdsMK2lrhc/edit).
Related to #84 

I only finish the CONTOUR function for 2D image in order to test the ability of "SET_CONTOUR_PARAMETERS" & "CONTOUR_IMAGE_DATA". 

The PER_CONTOUR_DATA_2D.test.ts did not work properly temporary yesterday afternoon, but it works fine from last night until now.

### CODE REVIEW

**Comment by zarda** [comment]
commited a fixed testing for the issue.

**Comment by kswang1029** [comment]
@acdo2002 is this for performance "monitoring"?

**Comment by acdo2002** [comment]
@kswang1029  This code is for testing the coverage (https://docs.google.com/document/d/1WhXQCLfctzaHA7uAgCG_YCrxAQO-cO3M8MJuNM_5xYQ/edit)
Yes, you can say it is part of the performance of monitoring.

**Comment by kswang1029** [comment]
@acdo2002 if it is for test coverage (which makes sure the backend does things right), then you should check coordinates for contour vertices in each case.

**Pull request merged**
