### PR TITLE
Testing resume

### PR DESCRIPTION
**Pull request by zarda**
For #141, the most tests for resume session are done. The resume moments will be implemented until the feature in backend is done.
Corrected the logic in the function to Client.streamUntil(isDone) so we can receive stream until isDone==True.

### CODE REVIEW

**Comment by acdo2002** [comment]
ANIMATOR_CONTOUR*.test.ts & RESUME*.test.ts are all PASSED with socketdev & socketicd.
However RESUME_CATALOG.test.ts is failed with ws. (let testServerUrl = config.serverURL0;)
Other RESUME*.test.ts work fine.

In addition, should we keep the config.timeout.playImages? because CONTOUR_DATA_STREAM.test.ts & PER_CONTOUR_DATA_2D.test.ts are still using it. or we just replace playImages by renderImages to those tests?

**Comment by zarda** [comment]
> ANIMATOR_CONTOUR*.test.ts & RESUME*.test.ts are all PASSED with socketdev & socketicd.
> However RESUME_CATALOG.test.ts is failed with ws. (let testServerUrl = config.serverURL0;)
> Other RESUME*.test.ts work fine.
This testing needs an additional image and the xml file.

> 
> In addition, should we keep the config.timeout.playImages? because CONTOUR_DATA_STREAM.test.ts & PER_CONTOUR_DATA_2D.test.ts are still using it. or we just replace playImages by renderImages to those tests?
Corrected it, thanks.

**Review by ajm-asiaa — APPROVED** [review]
Nice. All tests seem to work fine on MacOS

CI=true npm test src/test/ANIMATOR_CONTOUR.test.ts
CI=true npm test src/test/ANIMATOR_CONTOUR_MATCH.test.ts
CI=true npm test src/test/RESUME_CATALOG.test.ts
CI=true npm test src/test/RESUME_CONTOUR.test.ts
CI=true npm test src/test/RESUME_IMAGE.test.ts
CI=true npm test src/test/RESUME_REGION.test.ts

**Review by acdo2002 — APPROVED** [review]
Now RESUME_CATALOG.test.ts works fine with socketicd 👍

**Pull request merged**
