### PR TITLE
Actions for benchmark

### PR DESCRIPTION
**Pull request by zarda**
Give a series of action to operate the CARTA backend and then get the benchmark of elapsed time and performance for #105.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@zarda Would it be a good idea to have a script that runs each test sequentially? 
Otherwise, I think the way to run it is one at a time; `CI=true npm test src/action/Animator.test.ts ` etc. ?

So far I have a problem with `src/action/Animators.test.ts`. While it is running, the backend keeps reporting: 

> Problem getting tile layer=3, x=1, y=3
> Problem getting tile layer=3, x=4, y=4
> Problem getting tile layer=3, x=3, y=5
> Problem getting tile layer=3, x=0, y=3
> Problem getting tile layer=3, x=4, y=5

At first I thought maybe I had an outdated or missing image, but here I am running the carta-backend on the ubuntu 'cartaviewer' server, so it should be using the same image pool as the 'carta' server. 
Anyway, I think it would also be good to have a list of images with their paths, that the tests use. e.g. `set_QA_performanc/cube_A/cube_A_01600_z00100.fits` Then if anyone at a different institute wants to repeat the tests, they know exactly which image they need.

Also, what is `"port": 5011, `in `src/action/config.json"` needed for?

**Comment by zarda** [comment]
> @zarda Would it be a good idea to have a script that runs each test sequentially?
> Otherwise, I think the way to run it is one at a time; `CI=true npm test src/action/Animator.test.ts ` etc. ?
Good idea, but there is an issue at the moment to block this. There are some tests which may hang on the backend because of the reading timeout. In the meanwhile, a failed test will block the other ones after. After tuning the timeout, we should have it in the next update.
> 
> So far I have a problem with `src/action/Animators.test.ts`. While it is running, the backend keeps reporting:
> 
> > Problem getting tile layer=3, x=1, y=3
> > Problem getting tile layer=3, x=4, y=4
> > Problem getting tile layer=3, x=3, y=5
> > Problem getting tile layer=3, x=0, y=3
> > Problem getting tile layer=3, x=4, y=5
> 
> At first I thought maybe I had an outdated or missing image, but here I am running the carta-backend on the ubuntu 'cartaviewer' server, so it should be using the same image pool as the 'carta' server.
This may be a bug about the acquiring tiles, we should look into a proper scale of tile, which may not good for small image. Will fix it in the next update. 
> Anyway, I think it would also be good to have a list of images with their paths, that the tests use. e.g. `set_QA_performanc/cube_A/cube_A_01600_z00100.fits` Then if anyone at a different institute wants to repeat the tests, they know exactly which image they need.

Will have a setting of path.
> 
> Also, what is `"port": 5011, `in `src/action/config.json"` needed for?
Before starting a test, the script will launch a new backend, which has a port: 5011.

**Comment by ajm-asiaa** [comment]
@zarda I don't know how to run the tests beginning with `Exec_`. Do you have any instructions?

Regarding the other non-`Exec_` tests, the following seem to run fine:
> Animator.test.ts
> Contour.test.ts
> CubeHistogram.test.ts
> LoadImage.test.ts
> LoadImages.test.ts
> Resume.test.ts
> Z-ProfileCursor.test.ts
> Z-ProfileRegion.test.ts
> ZoomIn.test.ts
> ZoomOut.test.ts

However, `Animators.test.ts` fails in most if its tests. It seems to fail in different tests each time.

`CubeHistograms.test.ts` also fails. It seems to cause a segmentation fault in the backend with the 6400x6400 image every time:

> Load 51200x51200 image to cache in 20882.025 ms at 125.53572 MPix/s
> Fill image histogram in 15482.864 ms at 169.31235 MPix/s
> Load 25600x25600 image to cache in 5247.261 ms at 124.89564 MPix/s
> Fill image histogram in 3369.306 ms at 194.5089 MPix/s
> Load 12800x12800 image to cache in 1241.251 ms at 131.99586 MPix/s
> Fill image histogram in 815.2950000000001 ms at 200.95793 MPix/s
> Load 6400x6400 image to cache in 313.404 ms at 130.69392 MPix/s
> Segmentation fault (core dumped)

Does `Animators.test.ts` and `CubeHistograms.test.ts` work fine for you?

**Comment by zarda** [comment]
> @zarda I don't know how to run the tests beginning with `Exec_`. Do you have any instructions?

Ok, I will have a instruction later.
About Exec_.. tests, we need to execute a backend. We need to address some paths: the pagecache blocker, backend, and image base  in `SocketOperation.ts`.
let commandPath: string = "/usr/local/bin/pagecache-management.sh";
let backendPath: string = "/home/hengtai/carta-backend/build/carta_backend";
let basePath: string = "/almalustre/carta/images";
> 
> Regarding the other non-`Exec_` tests, the following seem to run fine:
> 
> > Animator.test.ts
> > Contour.test.ts
> > CubeHistogram.test.ts
> > LoadImage.test.ts
> > LoadImages.test.ts
> > Resume.test.ts
> > Z-ProfileCursor.test.ts
> > Z-ProfileRegion.test.ts
> > ZoomIn.test.ts
> > ZoomOut.test.ts
> 
> However, `Animators.test.ts` fails in most if its tests. It seems to fail in different tests each time.
> 
> `CubeHistograms.test.ts` also fails. It seems to cause a segmentation fault in the backend with the 6400x6400 image every time:
> 
> > Load 51200x51200 image to cache in 20882.025 ms at 125.53572 MPix/s
> > Fill image histogram in 15482.864 ms at 169.31235 MPix/s
> > Load 25600x25600 image to cache in 5247.261 ms at 124.89564 MPix/s
> > Fill image histogram in 3369.306 ms at 194.5089 MPix/s
> > Load 12800x12800 image to cache in 1241.251 ms at 131.99586 MPix/s
> > Fill image histogram in 815.2950000000001 ms at 200.95793 MPix/s
> > Load 6400x6400 image to cache in 313.404 ms at 130.69392 MPix/s
> > Segmentation fault (core dumped)
> 
> Does `Animators.test.ts` and `CubeHistograms.test.ts` work fine for you?

There are still some testing images, which make the test failure. The reason is timeout. I didn't block them because it may pass sometimes. If we run one image at once, these tests may pass. My solution is to re-try and collect passed results only.

**Comment by acdo2002** [comment]
I haven't try [pagecache-management](https://github.com/svn2github/pagecache-management) successfully. 
Following are the preliminary results for non Exec_*.txt

Socketdev FAIL tests, others PASS:
```
Animators.test.ts
CubeHistograms.test.ts
```

Socketicd FAIL tests, others PASS:
```
Animators.test.ts
CubeHistograms.test.ts (will induce segmentation fault)
```

**Comment by zarda** [comment]
> I haven't try [pagecache-management](https://github.com/svn2github/pagecache-management) successfully.

It is ok if not running `pagecache-management`, which needs to execute by following sudo.
While not using `pagecache-management`, it needs following modification in `SocketOperation.ts.`
```
let commandPath: string = "/Users/zarda/GitHub/carta-backend-nrao/build/carta_backend";
let backendPath: string = "debug=1";
let basePath: string = "/almalustre/carta/images";
```

> Following are the preliminary results for non Exec_*.txt
> 
> Socketdev FAIL tests, others PASS:
> 
> ```
> Animators.test.ts
> CubeHistograms.test.ts
> ```

Longer timeout might let it pass, or we can skip those very large images.
> 
> Socketicd FAIL tests, others PASS:
> 
> ```
> Animators.test.ts
> CubeHistograms.test.ts (will induce segmentation fault)
> ```

**Comment by acdo2002** [comment]
I used two methods to test, one is server-to-server (client-side is acdc, and server-side is socketdev) and another is server itself (client-side and server-side are both acdc).

(1) server-to-server (client-side is acdc, and server-side is socketdev)
FAILED may vary in different tests (no overlap indicates that it may be ok with the code itself)
```
Exec_ZoomInImages.test.ts
```

FAILED
```
Animators.test.ts  
CubeHistograms.test.ts
Exec_Contour.test.ts 
Exec_ContourImages.test.ts
Exec_CubeHistogram.test.ts
Exec_ResumeImages.test.ts
Exec_Z-ProfileCursorImages.test.ts  
Z-ProfileRegion.test.ts
```

No response (waiting 1hr, there is no output)

```
Exec_Z-ProfileRegionImages.test.ts
Exec_CubeHistogramImages.test.ts
```

I will update the server itself (client-side and server-side are both acdc) later, Hengtai is using this method to develop the action for benchmark.

**Comment by acdo2002** [comment]
Note: I monitor the backend on specific port with `htop`, then I can check whether the testing is still running or not. 
Here is the update testing result with the server itself via socketicd (client-side and server-side are both acdc at carta viewer).

FAILED (testing with latest `dev` branch)

```
Animators.test.ts
Resume.test.ts
Exec_Resume.test.ts   
Exec_Contour.test.ts *1   
Exec_CubeHistogram.test.ts 
CubeHistograms.test.ts *2
Exec_CubeHistogramImages.test.ts (running time around 23hr)
Exec_ZoomInImages.test.ts  
Z-ProfileRegion.test.ts
Exec_Z-ProfileRegion.test.ts 
Exec_ResumeImages.test.ts                     
Exec_Z-ProfileCursorImages.test.ts  
Exec_Z-ProfileRegionImages.test.ts
Exec_ContourImages.test.ts  
```
*1  Failed # [9,6,7,5,4,3,7,5,3,7], 40 in total. the failed number varies on the continuous running.
*2 Running this test (including calling 6 images) will induced the segmentation fault. However if run each image individually, the backend will still alive, no crash. But the SetTimeOut is still too short for the first 2 largest images.

If I change the backend version to `b3f1ade`, the above tests are all failed. In addition, 
```
Exec_Animators.test.ts 
Exec_ZoomOutImages.test.ts
```
will also become failed.

**Comment by zarda** [comment]
Some failures due to the update of backend so we need to merge and update testing as well.

**Pull request merged**
