### PR TITLE
Testing contour

### PR DESCRIPTION
**Pull request by zarda**
For #104, the tests for the feature: contour.
Add new support js library: [ZstdCodec](https://github.com/yoshihitoh/zstd-codec) to extract the raw data from backend, and new functionality to unshuffle the extracted data.

### CODE REVIEW

**Comment by acdo2002** [comment]
Hi @zarda ,
I have updated the node_modules with your updated package.json.
New package/dependence of "zstd-codec" so far works fine with those contour related tests. 
But I have to study about this new zstd-codes a little bit...
At least, all of the *.test.ts are passed.

**Comment by ajm-asiaa** [comment]
@zarda Does something different need to be done to run these tests?
I tried with both the standard system "npm", and the "npm" with Emscripten. 
Maybe I'm missing something?

I'm having most success with `CONTOUR_IMAGE_DATA.test.ts`, but some tests are failing:

> FAIL src/test/CONTOUR_IMAGE_DATA.test.ts
>   CONTOUR_IMAGE_DATA test: Testing if contour image data (vertices) are delivered correctly
>     ✓ prepare zstd (1776ms)
>     Go to "set_QA" folder
>       SET_CONTOUR_PARAMETERS0 with SmoothingMode:"GaussianBlur"
>         ✕ should return CONTOUR_IMAGE_DATA x1 (5ms)
>         ✓ fileId = 0 (1ms)
>         ✓ referenceFileId = 0
>         ✓ progress = 1 (1ms)
>         ✓ len(contourSet) = 1
>         ✓ contourSets[0].level = 0.6
>         ✓ contourSets[0].decimationFactor = 4
>         ✓ contourSets[0].uncompressedCoordinatesSize = 104
>         ✕ number of contour vertices = 13 (1ms)
>         ✕ assert contour vertices
>       SET_CONTOUR_PARAMETERS1 with SmoothingMode:"BlockAverage"
>         ✕ should return CONTOUR_IMAGE_DATA x1 (2ms)
>         ✓ fileId = 0
>         ✓ referenceFileId = 0
>         ✓ progress = 1 (1ms)
>         ✓ len(contourSet) = 1
>         ✓ contourSets[0].level = 0.6
>         ✓ contourSets[0].decimationFactor = 4
>         ✓ contourSets[0].uncompressedCoordinatesSize = 40
>         ✕ number of contour vertices = 5
>         ✕ assert contour vertices (1ms)
>       SET_CONTOUR_PARAMETERS2 with SmoothingMode:"NoSmoothing"
>         ✕ should return CONTOUR_IMAGE_DATA x1 (1ms)
>         ✓ fileId = 0 (1ms)
>         ✓ referenceFileId = 0
>         ✓ progress = 1
>         ✓ len(contourSet) = 1
>         ✓ contourSets[0].level = 0.85
>         ✓ contourSets[0].decimationFactor = 4
>         ✓ contourSets[0].uncompressedCoordinatesSize = 104
>         ✕ number of contour vertices = 13 (1ms)
>         ✕ assert contour vertices
> 
>   ● CONTOUR_IMAGE_DATA test: Testing if contour image data (vertices) are delivered correctly › Go to "set_QA" folder › SET_CONTOUR_PARAMETERS0 with SmoothingMode:"GaussianBlur" › should return CONTOUR_IMAGE_DATA x1
> 
>     TypeError: Cannot read property 'slice' of null
> 
>       202 | 
>       203 |                     if (contour.contourSets[0].decimationFactor > 0) {
>     > 204 |                         floatData = unshuffle(new Uint8Array(zstdSimple.decompress(ContourImageData.contourSets[0].rawCoordinates).slice().buffer), 4.0);
>           |                                                              ^
>       205 |                     } else {
>       206 |                         floatData = Array.from(new Float32Array(ContourImageData.contourSets[0].rawCoordinates.slice().buffer));
>       207 |                     }
> 
>       at Object.<anonymous> (src/test/CONTOUR_IMAGE_DATA.test.ts:204:62)
>

**Comment by zarda** [comment]
@ajm-asiaa This PR does not need Emscripten but `npm install` before running to add new library "zstd-codec".
You could check if this lib is ready on `package.json`. Thank you for testing.

**Comment by acdo2002** [comment]
@ajm-asiaa 
I did not pass the tests at the first time. then I go to `carta-backend-ICD-test/` and type `npm install zstd-codec`
Then I can pass the tests.
The `package.json` should look like (from my laptop): 
...
"dependencies": {
        "procfs-stats": "^1.0.2",
        "react-scripts": "^3.4.1",
        "usage": "^0.7.1",
        "zstd-codec": "^0.1.2"
    },
...

**Comment by ajm-asiaa** [comment]
@acdo2002 Thanks.

I still just can't figure it out. The config.json does indeed contain` "zstd-codec": "^0.1.2"`.

After doing `npm install zstd-codec`, it ends up with:
> FAIL src/test/CONTOUR_IMAGE_DATA.test.ts
>   ● Test suite failed to run
> 
>     Cannot find module 'carta-protobuf' from 'CONTOUR_IMAGE_DATA.test.ts'
> 
>     > 1 | import { CARTA } from "carta-protobuf";
>         | ^
>       2 | 
>       3 | import { Client, AckStream, ProcessContourData } from "./CLIENT";
>       4 | import config from "./config.json";

So I need to do `./protobuf/build_proto.sh` again. But then the result is the same as earlier with not all tests passing.

**Comment by ajm-asiaa** [comment]
When I was doing the above unsuccessfully, I was running the ICD tests on MacOS connecting to a backend running on Ubuntu. 

Now I am running the ICD tests on CentOS7 and connecting the a backend running on MacOS. The 3 new Contour tests are now passing in this situation. 

So I wonder if the problem could be `zstd-codec` running on MacOS?

**Comment by acdo2002** [comment]
Hi @ajm-asiaa ,
Based on the output:
`Cannot find module 'carta-protobuf' from 'CONTOUR_IMAGE_DATA.test.ts'`
I guess the problem is that it cannot find the carta-protobuf, you can to go to `carta-backend-ICD-test/protobuf` and `./build_proto.sh` again (after you `npm install zstd-codec`). It will create a lib of carta-protobuf under the carta-backend-ICD-test/node_modules.

**Comment by ajm-asiaa** [comment]
I'm also having trouble running the new Contour ICD tests on CentOS7 with the backend running on MacOS.

I copied over the required image files (because the MacOS system does not have access to the sample images on the Lustre disk array).
**contour_test.miriad** for `CONTOUR_IMAGE_DATA.test.ts`
**contour_test_nan.image** for `CONTOUR_IMAGE_DATA_NAN.test.ts`
**h_m51_b_s05_drz_sci.fits** for `CONTOUR_DATA_STREAM.test.ts`

Running each contour test results in a segmentation fault on the backend.

`CONTOUR_IMAGE_DATA.test.ts`:
> Session 1 (Wed Jul  1 09:23:42 2020): Client 1 [::ffff:127.0.0.1] Connected. Num sessions: 1
> Load 21x21 image to cache in 0.611 ms at 0.721768 MPix/s
> Fill image histogram in 0.195 ms at 2.26154 MPix/s
> Nearest neighbour filter 21x21 raster data to 21x21 in 0.013 ms at 33.9231 MPix/s
> Compress 21x21 tile data in 0.061 ms at 7.22951 MPix/s
> Compress 21x21 tile data in 0.072 ms at 6.125 MPix/s
> Get tile data group in 0 ms
> Smoothed with smoothing factor of 4 and kernel size of 7 in 0.297 ms at 0.757576 MPix/s
> zsh: segmentation fault  ./carta_backend -port 3333 -threads 4 -omp_threads 4 -base  -root  -verbose  

`CONTOUR_IMAGE_DATA_NAN.test.ts`:
> Session 1 (Wed Jul  1 09:25:18 2020): Client 1 [::ffff:127.0.0.1] Connected. Num sessions: 1
> Load 19x22 image to cache in 0.479 ms at 0.872651 MPix/s
> Fill image histogram in 0.203 ms at 1.90148 MPix/s
> Nearest neighbour filter 22x19 raster data to 22x19 in 0.013 ms at 32.1538 MPix/s
> Compress 19x22 tile data in 0.06 ms at 6.96667 MPix/s
> Compress 19x22 tile data in 0.071 ms at 5.88732 MPix/s
> Get tile data group in 0 ms
> Smoothed with smoothing factor of 4 and kernel size of 7 in 0.057 ms at 3.64912 MPix/s
> zsh: segmentation fault  ./carta_backend -port 3333 -threads 4 -omp_threads 4 -base  -root  -verbose  

`CONTOUR_DATA_STREAM.test.ts`:

> Session 1 (Wed Jul  1 09:27:20 2020): Client 1 [::ffff:127.0.0.1] Connected. Num sessions: 1
> 2020-07-01 01:27:21	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> 2020-07-01 01:27:21	WARN	FITSImage::getImageAttributes (file /Users/acdc/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726FITS unit "ELECTRONS" unknown to CASA - will treat it as non-dimensional.
> 2020-07-01 01:27:21	WARN	FITSImage::getImageAttributes (file /Users/acdc/carta-casacore/casa6/casatools/casacore/images/Images/FITSImage.cc, line 726)+	 See http://fits.gsfc.nasa.gov/fits_standard.html for a list of valid units.
> Load 8600x12200 image to cache in 1215.35 ms at 86.329 MPix/s
> Fill image histogram in 786.157 ms at 133.459 MPix/s
> Fill spatial profile in 1 ms
> Mean filter 12200x8600 raster data to 191x135 in 1204.76 ms at 0.0214026 MPix/s
> Compress 135x191 tile data in 0.722 ms at 35.7133 MPix/s
> Compress 135x191 tile data in 0.731 ms at 35.2736 MPix/s
> Get tile data group in 1207 ms
> zsh: segmentation fault  ./carta_backend -port 3333 -threads 4 -omp_threads 4 -base  -root  -verbose  

The only good news is it helped me figure out one issue:
On the ubuntu server, the `h_m51_b_s05_drz_sci.fits` file is actually a symlink to a location that doesn't exist:
`h_m51_b_s05_drz_sci.fits -> /scratch/images/set_OIR/h_m51_b_s05_drz_sci.fits`
This is because on the ubuntu server, the almalustre mount point is different (/almalustre/carta/images/), whereas on the `carta` server it is /scratch/images. I have removed the symlink and copied the real image to that location. 
But unfortunately it doesn't fix the problems.

With the ICD tests running from MacOS and the backend running on ubuntu, only the `CONTOUR_DATA_STREAM.test.ts` test passes. The other two fail.

**Comment by zarda** [comment]
In case the MacOS made the error in zstd decode, it would be shown on the Jest. I am sure about the zstd-codec is able to run on Mac. In another side, it maybe the issue on the environment of back-end. In my usual testing, the client is Mac and the backend is on the carta demo server. I suppose that at least this combination will be good. Thanks for testing.

**Comment by ajm-asiaa** [comment]
I just realised, we currently need to build the MacOS version with `-DDisableContourCompression=true` otherwise contours don't work properly. 
So we should either try to fix the contours on the MacOS backend, or skip Contour related tests on MacOS.

**Comment by kswang1029** [comment]
better not to skip any tests

**Comment by ajm-asiaa** [comment]
Now that we have updated zstd from 0.5.1 to 1.3.1 on the Ubuntu server, I can confirm that the three new Contour tests work fine on Ubuntu (ICD tests on MacOS connecting to a backend running on Ubuntu).

Next we just need to fix the carta_backend contour rendering problem on MacOS. 

I know these ICD tests will probably work fine on MacOS once the backend problem is fixed, but we better make sure the backend problem is fixed first.

**Pull request merged**
