### PR TITLE
233 export image

### LINKED ISSUE #233: Export sub image
From backend issue [#618](https://github.com/CARTAvis/carta-backend/issues/618), the feature is merged at the moment.

ICD commands:
[SAVE_FILE](https://carta-protobuf.readthedocs.io/en/latest/messages.html#savefile)
[SAVE_FILE_ACK](https://carta-protobuf.readthedocs.io/en/latest/messages.html#savefileack)

To [test](https://docs.google.com/document/d/1tPyqQp8Rd2yH5bhdFT676nePbfLWVfF26_l3hKVHrAo/edit#):
- [x] Export a image in format of casa or fits
- [x] Export subimage in a spectral range of original image
- [x] Export subimage in a combination of stokes to original image
- [x] Export a chopped region of original image
- [x] Export a chopped region of shared image
- [x] Drop degenerated axes
- [x] Handle error as chop a region outside the image

To implement:

- [x] EXPORT_IMAGE_ORIGINAL
- [x] EXPORT_IMAGE_CHANNEL
- [x] EXPORT_IMAGE_STOKES
- [x] EXPORT_IMAGE_CHOP
- [x] EXPORT_IMAGE_CHOP_SHARED
- [x] EXPORT_IMAGE_DROP_DEG
- [x] EXPORT_IMAGE_ERROR_MESSAGE

### PR DESCRIPTION
**Pull request by zarda**
Close #233, test the feature of exporting sub-image.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@zarda I'm running into the same file permissions problem as in the [mylin/#233 export sub image](https://github.com/CARTAvis/carta-backend-ICD-test/pull/239) branch.

```
[2021-05-24 14:45:24.264] [info] Exported a FITS file '/almalustre/carta/images/tmp/M17_SWex_Chop.fits'.
[2021-05-24 14:45:24.438] [critical] filesystem error: cannot remove all: Permission denied [/almalustre/carta/images/tmp/M17_SWex_Chop.image]
```
On Linux, the file is being written to `/almalustre/carta/images/tmp`, by the first user, but then another user can not overwrite it due to file ownership permissions.
Also, when Jenkins is running, both the CentOS and Ubuntu system will be writing to the same location at the same time.

We solved these problem in the `mylin/#233 export sub image` branch by: 

1. Writing to the local /tmp folder instead. e.g.
```
let tmpdirectory: string = config.path.save;

outputFileDirectory: tmpdirectory,
````
2. Deleting the written files at the end of the test. e.g.
```
    afterAll(() => {
        Connection.close();
        describe(`Delete test image`,()=>{
            const output = execSync('rm -r /tmp/M17_SWex_Partial.image /tmp/M17_SWex_Partial.fits',{encoding: 'utf-8'});
            console.log(output);
        });
    });
```

Would you be able to use that way?

**Comment by acdo2002** [comment]
The main goal of ICD tests is applying them to the CI/CD, we should write the tests that can apply to each Ubuntu/CentOS/MacOS server rather than just fit it to the demo server.

**Comment by acdo2002** [comment]
@ajm-asiaa I have adjusted the codes to solve the permission problem, as well as making consistent between this branch and `mylin/#233 export_sub_image` branch, please check them!

**Comment by ajm-asiaa** [comment]
@acdo2002 Unfortunately I'm not having any luck with this. It doesn't give any matches with the snapshots. Both on MacOS and Ubuntu. For example,
```
    -     "size": "12914861",
    +     "size": "53008687",
        },
        "fileInfoExtended": Object {
          "computedEntries": Array [
            Object {
              "name": "Name",
              "value": "M17_SWex_Chop.image",
            },
            Object {
              "name": "Shape",
    -         "value": "[351, 351, 25, 1]",
    +         "value": "[640, 800, 25]",
```
It seems to be the same problem I had on the other branch. But now I'm running the carta_backend without `--top_level_folder`, so that shouldn't be the problem. What else could I be missing?

**Comment by acdo2002** [comment]
Now I run it on almac, both ws and wss (to CentOS) are all PASSED. 

I start the backend with `./carta_backend /Users/acdc/almalustre-images --omp_threads=4 --debug_no_auth=true --no_http=true --verbosity=5 --log_performance=true`

You can go to mingyi folder to test them. The carta-ICD-test folder is` /Users/mingyi/carta-ICD-Hengtai/src/test`

For the shape information, I think it does not write the image in the right way. I think it is permission problem related to the folder permission setting (should we ask the backend people?) since CentOS is passed right? why given the same execution command line, backend on different OS has different behavior?

**Comment by ajm-asiaa** [comment]
@acdo2002 I tried again, this time with newly cloned `carta-backend-ICD-test` repositories. Maybe the problem was an old protobuf version? Anyway, now the tests pass fine on MacOS and Ubuntu!

**Review by ajm-asiaa — APPROVED** [review]

**Review by acdo2002 — APPROVED** [review]

**Pull request merged**
