### PR TITLE
Testing implementation: match of xy & z

### PR DESCRIPTION
**Pull request by zarda**
From #134, add testing for matching feature of xy & z.

### CODE REVIEW

**Review by ajm-asiaa — CHANGES_REQUESTED** [review]
`MATCH_SPATIAL.test.ts` works on MacOS after copying over the `set_HD163296` directory.

However, there are problems with `MATCH_SPECTRAL.test.ts` and `MATCH_STATS.test.ts`. Looks like it is the problem of different values on MacOS again:

 `MATCH_SPECTRAL.test.ts`

      ✕ Assert the first profile equal to the last profile (11ms)

There is a long list of numbers. I better not copy and paste into here.

`MATCH_STATS.test.ts`
A few of the errors are:

    Expected: -8.47528956020534
    Received: -5.6031116547760575

    Expected precision:    3
    Expected difference: < 0.0005
    Received difference:   2.8721779054292824


    Expected: 0.023849444463849068
    Received: 0.022138090804219246

    Expected precision:    3
    Expected difference: < 0.0005
    Received difference:   0.0017113536596298218

I wonder what causes it?

**Comment by zarda** [comment]
The MATCH_SPECTRAL sometimes passes in my testing on macbook.
Possibly, it relates to the backend issue [#607](https://github.com/CARTAvis/carta-backend/issues/607).

**Comment by kswang1029** [comment]
> The MATCH_SPECTRAL sometimes passes in my testing on macbook.
> Possibly, it relates to the backend issue [#607](https://github.com/CARTAvis/carta-backend/issues/607).

#607 is only related to wide field images. The adopted images in the test are very unlikely the case.

**Comment by ajm-asiaa** [comment]
Good. `MATCH_STATS.test.ts` passes on MacOS now. 

Only one left to fix is `MATCH_SPECTRAL.test.ts`

**Comment by zarda** [comment]
Updated the failed tests, they should pass at the moment, thanks for inspection.
The main issue is that the returning messages are not always in the same order.

**Review by ajm-asiaa — APPROVED** [review]
Tests seem to pass fine in MacOS at least.

**Review by acdo2002 — APPROVED** [review]
Now I am testing the latest commit with socketicd on CentOS, they are all PASSED.

**Comment by kswang1029** [comment]
I am still giving comments on the test design and this PR has been merged. Why does this need to be merged now?

**Pull request merged**
