### PR TITLE
Mylin/#279 2d image fitting

### PR DESCRIPTION
**Pull request by acdo2002**
Finish #297 implementation, I used new images:
"M17_SWex-channel0-addOneGaussian.fits", "M17_SWex-channel0-addOneGaussian.image", "M17_SWex-channel0-addOneGaussian.hdf5" and "ThreeComponent-inclined-2d-gaussian.fits".

They can be downloaded in [here](https://drive.google.com/drive/folders/1Wi1WxXk6gg-aQQXhXTTEN8m8vM4bWMcX?usp=sharing)

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@mylin There are a few things that need to be adjusted

**macOS 12 M1:**

`IMAGE_FITTING_FITS.test.ts`, `IMAGE_FITTING_HDF5.test.ts` and `IMAGE_FITTING_CASA.test.ts` work fine.

The `IMAGE_FITTING_BAD.test.ts` test reports: 
```
    Expected: 137.4108664786717
    Received: 129.52934425744016

    Expected precision:    6
    Expected difference: < 5e-7
    Received difference:   7.881522221231535
```
Also, the backend log shows an error several times:
```
[CARTA] [error] gsl error: cholesky.c line645: matrix is not positive definite
```

**Ubuntu 20.04 and AlmaLinux 8.5:**

On both platforms `IMAGE_FITTING_FITS.test.ts` , `IMAGE_FITTING_HDF5.test.ts`, `IMAGE_FITTING_CASA.test.ts`, and `IMAGE_FITTING_FITS.test.ts` all report the same error:
```
    Expected: 319.498940837943
    Received: 319.49928522605194

    Expected precision:    6
    Expected difference: < 5e-7
    Received difference:   0.00034438810894243943
```
On these platforms, the backend log shows no errors.

**Comment by kswang1029** [comment]
Please ignore 
[CARTA] [error] gsl error: cholesky.c line645: matrix is not positive definite

**Comment by acdo2002** [comment]
@kswang1029 
It looks the Ubuntu 20.04 gsl return a slightly different results (difference ~ 0.0008 compared to MacOS 11 gsl) for image fitting. Could the precision for image fitting down to 0.005(digit precision of 2)

**Comment by kswang1029** [comment]
> @kswang1029
> It looks the Ubuntu 20.04 gsl return a slightly different results (difference ~ 0.0008 compared to MacOS 11 gsl) for image fitting. Could the precision for image fitting down to 0.005(digit precision of 2)

having small differences from different platforms is fine. Is it possible to have platform-dependent assertions?

**Comment by acdo2002** [comment]
@kswang1029 
Ideally yes, we have platformStrings in the RegisterViewerAck. 
However it only return "masOS" or "Linux"..., we cannot recognize it is MasOS 11 or MasOS 12 ...

Old method is, we can have different test files to different platforms, because the test file is plain txt and not so big.
However here the difference is quite small e-2 (i.e. Ubuntu 20.04 and AlmaLinux 8.5, I may suggest to change the precision to 2 in `IMAGE_FITTING*.test.ts`)

However `IMAGE_FITTING_BAD.test.ts` have a big different(~7.881522221231535) for "exceeded max number of iterations" on MacOS 12. I will write another for specific MacOS 12 platform.

**Comment by acdo2002** [comment]
@ajm-asiaa Could you re-test them in all the platforms?
I adjust the precision to 0.005 (digit of 2), hope `IMAGE_FITTING_FITS.test.ts` , `IMAGE_FITTING_HDF5.test.ts`, and `IMAGE_FITTING_CASA.test.ts` can work for all platform...

About `IMAGE_FITTING_BAD.test.ts`, because it is testing the bad input and exceeded max number of iterations, it looks different OS may return different values.
I make `IMAGE_FITTING_BAD_MACOS12.test.ts` for MasOS 12 and `IMAGE_FITTING_BAD_Ubuntu2004.test.ts` for Ubuntu 20.04.

**Comment by ajm-asiaa** [comment]
@acdo2002 Do we also run the `IMAGE_FITTING_BAD_Ubuntu2004.test.ts` test on AlmaLinux 8?
It passes on AlmaLinux 8, but the original `IMAGE_FITTING_BAD.test.ts` does not, so maybe we need to rename it to IMAGE_FITTING_BAD_linux.test.ts?

Apart from that, all the tests now pass on macOS12, Ubuntu 20.04, and AlmaLinux 8!

It is a bit unfortunate that we need to use different tests for different platforms because the matrix configuration in the `Jenkinsfile-full` simply sends the same list of tests to each of the 7 platforms, but we can probably make it work with some if-loops.

**Comment by acdo2002** [comment]
@ajm-asiaa Sorry I cannot recognize MacOS 11 and 12 from the ICD message flow, I only apply the old method to solve this problem. So the Jenkins needs to use different tests for different platforms.... I am sorry for it....

I have updated the name to  `IMAGE_FITTING_BAD_linux.test.ts`.

**Comment by kswang1029** [comment]
out of curiosity, is this with RxJS approach?

**Comment by acdo2002** [comment]
@kswang1029 Current is the original ICD approach. 
Let me finish this then transfer to RxJS (the only change is request/response, now we are fixing the number in different platforms, which is not related to request/response)

**Comment by acdo2002** [comment]
@ajm-asiaa 
I put `IMAGE_FITTING_BAD_MACOS12.test.ts` and `IMAGE_FITTING_BAD_linux.test.ts` into `IMAGE_FITTING_BAD.test.ts`.
Now `IMAGE_FITTING_BAD.test.ts` can check platform and MacOS version to do the matching, could you check whether `IMAGE_FITTING_BAD.test.ts` work fine in all the platform?

Once you confirmed it, I will delete `IMAGE_FITTING_BAD_MACOS12.test.ts` and `IMAGE_FITTING_BAD_linux.test.ts` on this branch!

**Comment by ajm-asiaa** [comment]
@acdo2002 I confirm that the four IMAGE_FITTING tests work on Ubuntu 20.04 and AlmaLinux 8, but unfortunately `IMAGE_FITTING_BAD.test.ts` is not working on macOS12. 

At first the backend was crashing with a segmentation fault. But I'm not sure if it was related to this test or due to some other reason. Then Jest was refusing to connect to the backend for any test, even though the backend was running: `Error: connect ECONNREFUSED 127.0.0.1:3333`. I fixed it by using the Activity Monitor to kill the 'java' process that was running. After that process was stopped, Jest could connect to the backend and run tests again. 

Now that things are working again, the test is giving this error:
```
    Expected: 137.4108664786717
    Received: 129.52934425744016

    Expected precision:    2
    Expected difference: < 0.005
    Received difference:   7.881522221231535
```

I also tried on macOS11. There, the CASA, FITS, and HDF5 image fitting tests work, but not `IMAGE_FITTING_BAD.test.ts`. It failed with:
```
    Expected: 137.4108664786717
    Received: 101.25754777255497

    Expected precision:    2
    Expected difference: < 0.005
    Received difference:   36.15331870611672
```

**Comment by acdo2002** [comment]
@ajm-asiaa 
I have slightly modified `IMAGE_FITTING_BAD.test.ts`, could you try this on macOS12 again?

I am a little bit worry macOS11, since my laptop is macOS11 and it passed.
Could you kindly put the 4 testing images (`ThreeComponent-inclined-2d-gaussian.fits`, `M17_SWex-channel0-addOneGaussian.fits`, `M17_SWex-channel0-addOneGaussian.image`, and `M17_SWex-channel0-addOneGaussian.hdf5`) to `/Users/acdc/almalustre-images`, then I can test almac directly? 
I found almac is macOS11.

**Comment by ajm-asiaa** [comment]
@acdo2002 The `IMAGE_FITTING_BAD.test.ts` test works on macOS12 now!

I have copied the new test images to 'almac' now. I just tried the test on it and get: 
```
    Expected: 137.4108664786717
    Received: 136.49556911082368

    Expected precision:    2
    Expected difference: < 0.005
    Received difference:   0.9152973678480123
```

The macOS11 system that I originally ran the test on, and that is giving different values, is another computer. I will create a personal account on it for you now.

**Comment by acdo2002** [comment]
@ajm-asiaa 
I have modified the `IMAGE_FITTING_BAD.test.ts` to fit the macOS 11.6.1.
It seems gsl lib return different value for bad input in different macOS 11 (at least my masOS 11.6 laptop is different to the one macOS 11.6.1 you used).
please check it whether work fine now, thanks!

**Review by ajm-asiaa — APPROVED** [review]
Nice work @acdo2002. I confirm that all 4 new ICD pass on Ubuntu 20.04, AlmaLinux 8, plus the macOS11 and macOS12 systems.

I haven't checked with the Linux Docker containers that Jenkins actually runs, but I imagine it will be OK.

Soon I will add these tests as a new stage to the Jenkinsfile-full.

**Pull request merged**
