### PR TITLE
Mylin/#201 compare hdf5 fileinfo to fits

### PR DESCRIPTION
**Pull request by acdo2002**
Implementation of issue #201 .

### CODE REVIEW

**Comment by acdo2002** [comment]
Fixed the issue #201 .
I think this file is not necessary to be included in Jenkins.
But this file would be good in the ICD repository once we want to see the difference in header entries between FITS & HDF5 files.

**Comment by ajm-asiaa** [comment]
@acdo2002 Do you have the `SDC335.579-0.292.spw0.line.hdf5` file? I can't seem to find it anywhere.

**Comment by acdo2002** [comment]
Yes, I have it.
It locates on acdc server: `/scratch/images/set_QA/SDC335.579-0.292.spw0.line.hdf5`
`SDC335.579-0.292.spw0.line.fits` is also at the same directory.

**Review by ajm-asiaa — APPROVED** [review]
Works well on MacOS and Ubuntu.

**Pull request merged**
