### PR TITLE
Revert "Mylin/#314 improve image bad fitting redhat9"

### PR DESCRIPTION
**Pull request by ajm-asiaa**
Reverts CARTAvis/carta-backend-ICD-test#315

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
@acdo2002 Unfortunately it didn't pass on Redhat 7 and RedHat 8. Both RedHat 7 and RedHat 8 say:
```
    Expected: 141.19569242428403
    Received: 135.44304395891785

    Expected precision:    2
    Expected difference: < 0.005
    Received difference:   5.752648465366178
```
I guess they are no longer being considered as the previous `Linux` platform?

**Comment by kswang1029** [comment]
do they have the same GSL version?

**Comment by ajm-asiaa** [comment]
RedHat9 uses GSL 2.6
RedHat8 uses GSL 2.5
RedHat7 uses GSL 2.5 via our carta-gsl
Ubuntu 22.04 uses GSL 2.7

**Comment by acdo2002** [comment]
@ajm-asiaa Could you give me the Redhat 7 and Redhat 8 Docker images, then I can test them tomorrow.

**Comment by ajm-asiaa** [comment]
OK. Thanks!
`docker run -ti ajmasiaa/rhel8-jenkins-apr2022`
`docker run -ti ajmasiaa/rhel7-jenkins-apr2022`

**Comment by acdo2002** [comment]
@ajm-asiaa 
Hi Anthony,
I have modified the criteria condition in order to let the test passed in RedHat 7 & RedHat 8.
Please check the test file should be worked fine on RedHat 7, 8, 9.
If there is any failure please let me know, I can modify the test.

**Comment by ajm-asiaa** [comment]
@acdo2002 I tested on Red Hat 8 and Ubuntu 22.04. It works fine on those. 
I'll take a shortcut again and merge it so that Jenkins will test automatically on all 8 platforms.

**Pull request merged**
